version: '1.0'
services:
  postgres:
    image: postgres:13.3
    env_file:
      - "postgres.env"
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    container_name: unlock_pgdb
  unlock-bot:
    image: romaaaka/unlockbot:v1-prod
    command: "python unlockbot.py"
    ports:
      - "8001:8001"
    env_file:
      - ".env"
    depends_on:
      - postgres
    volumes:
      - C:\home\unlock\telegram-bot\logs:/app/logs
volumes:
  postgres: